projects:
  prod:
    schemaPath: schema/schema.graphql
    extensions:
      endpoints:
        default: https://api.vendobox.com.au/graphql
  dev:
    schemaPath: schema/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4001/graphql
